# Generated by Django 4.2.10 on 2026-03-28 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('hiring', '🔍 Hľadanie zamestnanca'), ('investment', '💰 Hľadanie investora'), ('consulting', '📊 Konzultácia'), ('marketing', '📢 Marketing pomoc'), ('speaking', '🎤 Speaking príležitosť'), ('networking', '🤝 Networking'), ('sales', '💼 Sales podpora'), ('other', '❓ Ostatné')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='❓', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('expertise', models.CharField(help_text='Odbornosti oddelené čiarkami (napr: React, Python, GTM, Sales)', max_length=500)),
                ('availability', models.CharField(choices=[('high', 'Vysoká (hoc-aj denne)'), ('medium', 'Stredná (niekoľko hodín mesiac)'), ('low', 'Nízka (len keď je čas)')], default='medium', max_length=20)),
                ('help_provided', models.IntegerField(default=0, help_text='Počet pomôcok, ktoré poskytol')),
                ('profile_image', models.ImageField(blank=True, upload_to='experts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requester_name', models.CharField(max_length=200)),
                ('requester_email', models.EmailField(max_length=254)),
                ('requester_phone', models.CharField(blank=True, max_length=20)),
                ('priority', models.CharField(choices=[('low', '🔵 Nízka'), ('medium', '🟡 Stredná'), ('high', '🔴 Vysoká'), ('critical', '🔴🔴 Kritická')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', '🟢 Otvorená'), ('in_review', '🟡 V preverovaní'), ('waiting_expert', '⏳ Čakanie na experta'), ('in_progress', '🟠 V riešení'), ('resolved', '✅ Vyriešená'), ('rejected', '❌ Zamietnutá')], default='open', max_length=20)),
                ('value_score', models.IntegerField(default=5, help_text='Očakávaný vplyv / hodnota (1-10)')),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('assigned_experts', models.ManyToManyField(blank=True, related_name='assigned_requests', to='server.expert')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.category')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('notification_type', models.CharField(choices=[('confirmation', 'Potvrdenie žiadosti'), ('expert_match', 'Match s expertem'), ('status_update', 'Aktualizácia statusu'), ('resolved', 'Žiadosť vyriešená')], max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.request')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0, help_text='Match score 0-100%')),
                ('reasoning', models.TextField(blank=True, help_text='Dôvod návrhu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.expert')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_matches', to='server.request')),
            ],
            options={
                'ordering': ['-match_score'],
                'unique_together': {('request', 'expert')},
            },
        ),
    ]
