# Generated by Django 4.2.10 on 2026-03-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='requester_type',
            field=models.CharField(choices=[('startup', '🚀 Startup'), ('investor', '💰 Investor'), ('service_provider', '🛠️ Poskytovateľ služieb'), ('community_member', '👥 Člen komunity')], default='community_member', max_length=20),
        ),
    ]
