# Generated by Django 4.2.10 on 2026-03-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_request_requester_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.RemoveField(
            model_name='expert',
            name='expertise',
        ),
        migrations.AddField(
            model_name='expert',
            name='rating',
            field=models.FloatField(default=0.0, help_text='Average user rating (0-5)'),
        ),
        migrations.AddField(
            model_name='expert',
            name='rating_count',
            field=models.IntegerField(default=0, help_text='Number of ratings'),
        ),
        migrations.AddField(
            model_name='expert',
            name='work_experience',
            field=models.TextField(blank=True, help_text='Work experience highlights'),
        ),
        migrations.AddField(
            model_name='request',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='request',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='request',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='is_corporate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='target_experience',
            field=models.CharField(blank=True, choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior'), ('lead', 'Lead')], max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('hiring', 'Hiring'), ('investment', 'Investment'), ('consulting', 'Consulting'), ('marketing', 'Marketing'), ('speaking', 'Speaking'), ('networking', 'Networking'), ('sales', 'Sales'), ('other', 'Other')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='availability',
            field=models.CharField(choices=[('high', 'High (daily)'), ('medium', 'Medium (weekly)'), ('low', 'Low (occasional)')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='expert',
            name='help_provided',
            field=models.IntegerField(default=0, help_text='Number of help contributions'),
        ),
        migrations.AlterField(
            model_name='request',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='requester_type',
            field=models.CharField(choices=[('corporate', 'Corporate'), ('startup', 'Startup'), ('investor', 'Investor'), ('service_provider', 'Service Provider'), ('community_member', 'Community Member')], default='community_member', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('waiting_expert', 'Waiting for Expert'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='value_score',
            field=models.IntegerField(default=5, help_text='Impact score (1-10)'),
        ),
        migrations.AddField(
            model_name='expert',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='experts', to='server.skill'),
        ),
        migrations.AddField(
            model_name='request',
            name='target_skills',
            field=models.ManyToManyField(blank=True, related_name='target_requests', to='server.skill'),
        ),
    ]
