# Generated by Django 4.2.10 on 2026-03-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_skill_remove_expert_expertise_expert_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.AddField(
            model_name='expert',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='experts', to='server.language'),
        ),
        migrations.AddField(
            model_name='request',
            name='required_languages',
            field=models.ManyToManyField(blank=True, related_name='required_by_requests', to='server.language'),
        ),
    ]
