# Generated by Django 4.2.10 on 2026-03-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_add_submitted_by_to_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='creator_resolved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when creator marked the request as done', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='is_resolved_by_creator',
            field=models.BooleanField(default=False, help_text='Whether the request creator has marked this as resolved/done'),
        ),
    ]
