# Generated by Django 4.2.10 on 2026-03-28 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_request_creator_resolved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='karma_points',
            field=models.IntegerField(default=0, help_text='Karma points earned for completed help'),
        ),
        migrations.AddField(
            model_name='request',
            name='completed_by_expert',
            field=models.ForeignKey(blank=True, help_text='Expert selected by creator as the one who completed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_requests', to='server.expert'),
        ),
    ]
