# Generated by Django 4.2.10 on 2026-03-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_expert_karma_points_request_completed_by_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='is_busy',
            field=models.BooleanField(default=False, help_text='Whether expert is currently assigned to an active request'),
        ),
    ]
