# Generated by Django 4.2.10 on 2026-03-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_expert_is_busy'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='offered_experts',
            field=models.ManyToManyField(blank=True, help_text='Experts who offered to help but are not assigned yet', related_name='offered_requests', to='server.expert'),
        ),
    ]
