# Generated by Django 4.2.10 on 2026-03-29 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0012_directchatmessage_companychatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_type', models.CharField(choices=[('company', 'Company Chat'), ('admin', 'Admin Chat'), ('direct', 'Direct Chat')], max_length=20)),
                ('last_read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('partner', models.ForeignKey(blank=True, help_text='Required for direct chat read-state rows', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_partner_read_states', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_read_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'chat_type', 'partner')},
            },
        ),
        migrations.CreateModel(
            name='ChatMuteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_type', models.CharField(choices=[('company', 'Company Chat'), ('admin', 'Admin Chat'), ('direct', 'Direct Chat')], max_length=20)),
                ('is_muted', models.BooleanField(default=False)),
                ('partner', models.ForeignKey(blank=True, help_text='Required for direct chat mute rows', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_partner_mute_settings', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_mute_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'chat_type', 'partner')},
            },
        ),
    ]
