# Generated by Django 4.2.10 on 2026-03-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_chatreadstate_chatmutesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminchatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='adminchatmessage',
            name='attachment_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='companychatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='companychatmessage',
            name='attachment_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='directchatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='directchatmessage',
            name='attachment_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='adminchatmessage',
            name='message',
            field=models.TextField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='companychatmessage',
            name='message',
            field=models.TextField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='directchatmessage',
            name='message',
            field=models.TextField(blank=True, default='', max_length=4000),
        ),
    ]
